name = "QuantizedSystemSolver"
uuid = "1012ed6b-4eb4-43ec-b9f7-8dc4179649a3"
authors = ["mongi bellili"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
